---
- name: Windows cleanup...
  ansible.builtin.include_tasks: windows.yml
  when: "'os_windows' in group_names"

- name: Linux cleanup...
  ansible.builtin.include_tasks: linux.yml
  when: "'os_linux' in group_names"

- name: Vyos cleanup...
  ansible.builtin.include_tasks: vyos.yml
  when: "'os_vyos' in group_names"
