---
- name: Listing all secrets for {{ project_fullname }} KV store...
  ansible.builtin.uri:
    url: "{{ vault_path }}"
    method: GET
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ auth.json.auth.client_token }}"
    body_format: json
    validate_certs: "{{ validate_vault_certs }}"
  register: existing_secrets
  delegate_to: localhost

- name: Adding {{ pregen_secret.key }} secret to {{ project_fullname }}...
  ansible.builtin.uri:
    url: "{{ vault_path }}"
    method: PATCH
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ auth.json.auth.client_token }}"
      Content-Type: application/merge-patch+json
    body:
      data: '{ "{{ pregen_secret.key }}": "{{ pregen_secret.value }}" }'
    body_format: json
    validate_certs: "{{ validate_vault_certs }}"
  delegate_to: localhost
  when: pregen_secret.key not in existing_secrets.json.data.data

- name: Checking if {{ pregen_secret.key }} was successfully added...
  ansible.builtin.uri:
    url: "{{ vault_path }}"
    method: GET
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ auth.json.auth.client_token }}"
    body_format: json
    validate_certs: "{{ validate_vault_certs }}"
  register: pregen_post_add_check
  delegate_to: localhost

- name: Re-including add_secrets task...
  ansible.builtin.include_tasks: add_secrets.yml
  when: pregen_secret.key not in pregen_post_add_check.json.data.data
