---
- name: Deleting snapshots removal tasks to localhost...
  delegate_to: localhost
  become: false
  block:
    - name: Removing {{ snapshot_name }} snapshot...
      community.vmware.vmware_guest_snapshot:
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "{{ custom_vm_name | default(vm_name) }}"
        state: absent
        snapshot_name: "{{ snapshot_name }}"
      when: not remove_all_snapshots | bool

    - name: Removing all existing snapshots...
      community.vmware.vmware_guest_snapshot:
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "{{ custom_vm_name | default(vm_name) }}"
        state: remove_all
      when: remove_all_snapshots | bool
