---
# Using VMware because vyos module isn't working & shell reboot is unstable
- name: Rebooting VM...
  community.vmware.vmware_guest_powerstate:
    folder: "{{ folder }}"
    name: "{{ custom_vm_name | default(vm_name) }}"
    state: reboot-guest
    force: true
  delegate_to: localhost
  become: false
  when:
    - reboot_on_finalize
    - infra_env == 'vsphere'
