---
- name: Including Ubuntu domain join tasks...
  ansible.builtin.include_tasks: ubuntu.yml
  when: "'os_ubuntu' in group_names"

- name: Including Windows domain join tasks...
  ansible.builtin.include_tasks: windows.yml
  when: "'os_windows' in group_names"
