---
- name: Installing Docker on Windows machine...
  ansible.builtin.include_tasks: windows.yml
  when: "'os_windows' in group_names"

- name: Installing Docker on Debian based Linux machine...
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts.os_family == "Debian"
