---
- name: Adding {{ item.key }} secret to {{ secrets_vault_secrets_path }}...
  ansible.builtin.uri:
    url: "{{ secrets_vault_data_fullpath }}"
    method: PATCH
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ auth.json.auth.client_token }}"
      Content-Type: application/merge-patch+json
    body:
      data: '{ "{{ item.key }}": "{{ item.value | default(generated_password_string) }}" }'
    body_format: json
    validate_certs: "{{ validate_vault_certs }}"
  delegate_to: localhost
  when: item.key not in existing_secrets.json.data.data

- name: Checking if {{ item.key }} was successfully added...
  ansible.builtin.uri:
    url: "{{ secrets_vault_data_fullpath }}"
    method: GET
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ auth.json.auth.client_token }}"
    body_format: json
    validate_certs: "{{ validate_vault_certs }}"
  register: pregen_post_add_check
  delegate_to: localhost

- name: Re-including add_secrets task...
  ansible.builtin.include_tasks: add_secrets.yml
  when: item.key not in pregen_post_add_check.json.data.data
