---
- name: Saving {{ admin_key_name }} password to Vault...
  ansible.builtin.include_tasks: save_secrets.yml
  vars:
    secrets:
      - key: "{{ admin_key_name }}"
        value: "{{ account.password | default(generated_password_string) }}"
  when:
    - admin_key_name not in existing_secrets.json.data.data
    - account.save_password_to_vault | default(true)
