---
- name: Delegating restart tasks to localhost...
  delegate_to: localhost
  become: false
  block:
    - name: Restarting {{ custom_vm_name | default(vm_name) }}...
      vmware.vmware_rest.vcenter_vm_guest_power:
        state: reboot
        vm: "{{ vcenter_vm_info.value[0].vm }}"
        session_timeout: 1800
      register: vcenter_vm_restart
      until: not vcenter_vm_restart.failed
      retries: 5
      delay: 2
      when: vcenter_vm_info.value[0].power_state != "POWERED_OFF"

    - name: Powering on {{ custom_vm_name | default(vm_name) }}...
      vmware.vmware_rest.vcenter_vm_power:
        state: start
        vm: "{{ vcenter_vm_info.value[0].vm }}"
      register: vcenter_vm_start
      until: not vcenter_vm_start.failed
      retries: 5
      delay: 2
      when: vcenter_vm_info.value[0].power_state == "POWERED_OFF"
