---
- name: Setting the following Windows Server registry values...
  ansible.windows.win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
  loop:
    - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Server\ServerManager # Not opening Server Manager at logon
      name: DoNotOpenAtLogon
      data: 1
      type: dword

  when:
    - ansible_facts.os_product_type == 'server' or ansible_facts.os_product_type == 'domain_controller'
    - ansible_facts.os_installation_type != 'Server Core'

- name: Setting the following Windows Server Core registry values...
  ansible.windows.win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
  loop:
    - path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon # Setting the shell to PowerShell.exe
      name: Shell
      data: PowerShell.exe -NoExit
      type: string

  when: ansible_facts.os_installation_type == 'Server Core'
