---
# Getting the the ADWS is up event after the last clean reboot
- name: Waiting until Active Directory Web Services is running...
  ansible.windows.win_shell: "{{ lookup('file', 'PostReboot-Check.ps1') }}"

- name: Getting domain info... # Extra check to make sure DC is up
  ansible.windows.win_shell: Get-ADDomain
  register: domain_check
  retries: 10
  delay: 5
  until: domain_check.rc == 0
