---
- name: Checking if {{ admin_key_name }} key is already present...
  ansible.builtin.uri:
    url: "{{ vault_path }}"
    method: GET
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ auth.json.auth.client_token }}"
    body_format: json
    status_code:
      - 200
      - 404
    validate_certs: "{{ validate_vault_certs }}"
  register: secrets_path
  delegate_to: localhost
  become: false

# Re-including this task until password passes validation - Uppercase,lowercase,number
- block:
    - block:
        - name: Including pwd generation task...
          ansible.builtin.include_tasks: generate_passwords.yml
      always:
        - ansible.builtin.include_tasks: save_admin_passwords.yml
          when: random_generated_pwd is not match('^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])')

    - name: Saving generated password for {{ admin_key_name }} to Vault...
      ansible.builtin.include_role:
        name: nova.core.save_secrets
      vars:
        secrets:
          - key: "{{ admin_key_name }}"
            value: "{{ item.password | default(random_generated_pwd) }}"
  when: secrets_path.status == 404 or admin_key_name not in secrets_path.json.data.data
