---
- name: Checking if {{ item.secret_key_name }} key is already present...
  ansible.builtin.uri:
    url: "{{ vault_path }}"
    method: GET
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ auth.json.auth.client_token }}"
    body_format: json
    status_code:
      - 200
      - 404
    validate_certs: "{{ validate_vault_certs }}"
  register: secrets_path
  delegate_to: localhost

- name: Saving generated secret for {{ item.secret_key_name }} to Vault...
  ansible.builtin.include_role:
    name: nova.core.save_secrets
  vars:
    secrets:
      - key: "{{ item.secret_key_name }}"
        value: "{{ item.secret_key_value | default(lookup('password', '/dev/null length=17 chars=ascii_lowercase,ascii_uppercase,digits')) }}"
  when: secrets_path.status == 404 or item.secret_key_name not in secrets_path.json.data.data
