---
primary_network: "{{ interfaces | selectattr('connection', 'equalto', true) | first }}"
connection_mode: "{{ primary_network.addresses | selectattr('connection', 'equalto', true) | map(attribute='mode') | first }}"
connection_mode_dhcp: "{{ true if connection_mode | regex_search('.*dhcp.*') else false }}"
