---
name: Adding a new version, tag & release

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  version_tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configuring collection & tag versions
        run: .github/update-version.sh

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.LATEST_TAG }}
          bodyFile: CHANGELOG.md
